version: 2
executorType: machine
jobs:
    build:
        steps:
            - checkout
            - run: chmod +x gradlew
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "build.gradle" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            # run tests!
            - run: ./gradlew clean generateJooq check --continue --console=plain
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "build.gradle" }}
        environment:
            GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
            _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
            TERM: dumb
